### ISSUE TITLE
Environment Variables for SMTP Server

### ISSUE THREAD

**Issue by nhalstead** [TheDonSaysNah/checkhomeIP#1]
Change username and password to be loaded from environment Variables.
Also change this to be generic for any SMTP server, in case people don't want to use GMail.

```
SMTP_HOST=
SMTP_USERNAME=
SMTP_PASSWORD=

RECHECK_INTERVAL=300
```

**Comment by TheDonSaysNah** [comment]
Would adding env vars be done like so:
```
use std::env;

fn main() {
    let key = "SMTP_HOST";
    env::set_var(key, "1");
}
```

**Comment by TheDonSaysNah** [comment]
This has now been added using a .env file.
